<a href="https://colab.research.google.com/github/LeoAzzE/DS-and-ML/blob/main/preProcessDeDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install plotly --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 79.1 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.15.0
    Uninstalling plotly-5.15.0:
      Successfully uninstalled plotly-5.15.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
base_credit = pd.read_csv('/content/credit_data.csv')

In [ ]:
base_credit

In [ ]:
base_credit.tail(10)

In [ ]:
base_credit.describe()

In [ ]:
base_credit[base_credit['income']>=69995.685578	]

In [ ]:
np.unique(base_credit['default'], return_counts=True)

In [ ]:
sns.countplot(x = base_credit['default']);

In [ ]:
plt.hist(x=base_credit['age']);

In [ ]:
plt.hist(x=base_credit['income'])

In [ ]:
plt.hist(x=base_credit['loan']);

In [ ]:
grafico = px.scatter_matrix(base_credit, dimensions=['age', 'income', 'loan'], color = 'default')
grafico.show()

In [ ]:
base_credit.loc[base_credit['age'] < 0]

In [ ]:
base_credit2 = base_credit.drop('age', axis = 1)
base_credit2

In [ ]:
base_credit3 = base_credit.drop(base_credit[base_credit['age'] < 0].index)
base_credit3

In [ ]:
base_credit['age'][base_credit['age'] > 0].mean()

40.92770044906149

In [ ]:
base_credit.loc[base_credit['age'] < 0, 'age']= 40.92

In [ ]:
base_credit.loc[base_credit['age'] < 0]

Empty DataFrame
Columns: [clientid, income, age, loan, default]
Index: []

In [ ]:
base_credit.head(33)

In [ ]:
base_credit.isnull()

In [ ]:
base_credit.isnull().sum()

In [ ]:
base_credit.loc[pd.isnull(base_credit['age'])]

In [ ]:
base_credit['age'].fillna(base_credit['age'].mean(), inplace = True)

In [ ]:
base_credit.loc[(base_credit['clientid'] == 29) | (base_credit['clientid'] == 31 | (base_credit['clientid'] == 32))]

In [ ]:
base_credit.loc[base_credit['clientid'].isin([29,31,32])]

In [ ]:
X_credit = base_credit.iloc[:, 1:4].values
X_credit

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [ ]:
X_credit[:,0].min()

In [ ]:
type (X_credit)

In [ ]:
Y_credit = base_credit.iloc[:, 4].values
Y_credit

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
X_credit[:,0].min(), X_credit[:,1].min(), X_credit[0:,2].min()

(20014.4894700497, -52.4232799196616, 1.37762959325451)

In [ ]:
X_credit[:,0].max(), X_credit[:,1].max(), X_credit[0:,2].max()

(1.7220222385319197, 1.7393673928651967, 3.0616609141708273)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler_credit = StandardScaler()
X_credit = scaler_credit.fit_transform(X_credit)

In [ ]:
base_census = pd.read_csv('/content/census.csv')

In [ ]:
base_census

In [ ]:
base_census.describe()

In [ ]:
base_census.isnull().sum()

In [ ]:
np.unique(base_census['income'], return_counts=True)

In [ ]:
sns.countplot(x=base_census['income'])

In [ ]:
plt.hist(x= base_census['age'])

In [ ]:
plt.hist(x = base_census['education-num'])

In [ ]:
plt.hist(x = base_census['hour-per-week'])

In [ ]:
grafico = px.treemap(base_census, path = ['workclass','age'])
grafico.show()

In [ ]:
grafico = px.treemap(base_census, path = ['occupation','relationship','age'])
grafico.show()

In [ ]:
grafico = px.parallel_categories(base_census, dimensions = ['occupation','relationship'])
grafico.show()

In [ ]:
grafico = px.parallel_categories(base_census, dimensions = ['workclass','occupation','income'])
grafico.show()

In [ ]:
base_census.columns

In [ ]:
X_census = base_census.iloc[:, 0:14].values
X_census

In [ ]:
X_census[0]

In [ ]:
Y_census = base_census.iloc[:, 14].values
Y_census

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder_teste = LabelEncoder()

In [ ]:
teste = label_encoder_teste.fit_transform(X_census[: , 1])
teste

array([7, 6, 4, ..., 4, 4, 5])

In [ ]:
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

In [ ]:
X_census[:,1] = label_encoder_workclass.fit_transform(X_census[:, 1])
X_census[:,3] = label_encoder_education.fit_transform(X_census[:, 3])
X_census[:,5] = label_encoder_marital.fit_transform(X_census[:, 5])
X_census[:,6] = label_encoder_occupation.fit_transform(X_census[:, 6])
X_census[:,7] = label_encoder_relationship.fit_transform(X_census[:, 7])
X_census[:,8] = label_encoder_race.fit_transform(X_census[:, 8])
X_census[:,9] = label_encoder_sex.fit_transform(X_census[:, 9])
X_census[:,13] = label_encoder_country.fit_transform(X_census[:, 13])

In [ ]:
X_census

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.1740e+03, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.3000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.5024e+04, 0.0000e+00,
        4.0000e+01]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
onehotencoder_census = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,3,5,6,7,8,9,13])], remainder='passthrough')

In [ ]:
X_census = onehotencoder_census.fit_transform(X_census).toarray()
X_census

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.1740e+03, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.3000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.5024e+04, 0.0000e+00,
        4.0000e+01]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
X_census = scaler_census.fit_transform(X_census)

In [ ]:
X_census[0]

array([-0.2444502 , -0.17429511, -0.26209736, -0.01466381, -1.5167923 ,
       -0.18838933, -0.29093568,  4.90769968, -0.02073999, -0.17175325,
       -0.19348662, -0.11609195, -0.07201601, -0.10164955, -0.1422718 ,
       -0.12664495, -0.18406376, -0.21053433,  2.25399324, -0.11334387,
       -0.68994199, -0.23637391, -0.03960742, -0.13419553, -0.53714425,
       -0.39750806, -0.02658695, -0.92284068, -0.11403678,  1.43105786,
       -0.1802846 , -0.17735813, -0.24494366,  2.76348874, -0.01662771,
       -0.37949517, -0.37774555, -0.17745022, -0.20957797, -0.25595432,
       -0.33554133, -0.06780164, -0.38166338, -0.14260848, -0.35531609,
       -0.17127887, -0.22710355, -0.82533335,  1.70899099, -0.17624972,
       -0.42934582, -0.34403232, -0.22492681, -0.09820087, -0.18155194,
       -0.32576824, -0.09161163,  0.4130197 , -0.70307135,  0.70307135,
       -0.13502327, -0.02416321, -0.06107342, -0.0480488 , -0.04260602,
       -0.05409379, -0.04641598, -0.02933708, -0.05714946, -0.05

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_credit_treinamento, X_credit_teste, Y_credit_treinamento, Y_credit_teste = train_test_split(X_credit, Y_credit, test_size = 0.25, random_state=0)

In [ ]:
X_credit_treinamento.shape

In [ ]:
Y_credit_treinamento.shape

In [ ]:
X_credit_teste.shape, Y_credit_teste.shape

((500, 3), (500,))

In [ ]:
# base de dados Census abaixo


In [ ]:
X_census_treinamento, X_census_teste, Y_census_treinamento, Y_census_teste = train_test_split(X_census, Y_census, test_size = 0.15, random_state=0)

In [ ]:
X_census_treinamento.shape, Y_census_treinamento.shape

((27676, 108), (27676,))

In [ ]:
X_census_teste.shape, Y_census_teste.shape

((4885, 108), (4885,))

In [ ]:
import pickle

In [ ]:
with open('credit.pkl', mode = 'wb') as f:
  pickle.dump([X_credit_treinamento,Y_credit_treinamento, X_credit_teste, Y_credit_teste], f)

In [ ]:
with open('census.pkl', mode = 'wb') as f:
  pickle.dump([X_census_treinamento, Y_census_treinamento, X_census_teste, Y_census_teste], f)